name: Publish Snapshot

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
    if: github.repository == 'Commit451/ResourcesPoet'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Retrieve version
        run: |
          echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Set credentials
        run: |
          echo "mavenCentralUsername=${{ secrets.SONATYPE_NEXUS_USERNAME }}\n" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.SONATYPE_NEXUS_USERNAME }}\n" >> gradle.properties

      - name: Publish snapshot
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')